services:
  my-application-training:
    build: ./organisation-proxy
    container_name: my-app-proxy
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
      interval: 10s
  my-config:
    build: ./profile-config
    container_name: my-config
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://my-application-training:8761/eureka
    depends_on:
      my-application-training:
        condition: service_healthy









